---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-namespace
  labels:
    environment: production
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-po
  namespace: myapp-namespace

  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
